version: "3"

services:
  django:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL=postgis://snufkin:secret@db:5432/snufkindb
    volumes:
      - .:/app
    command: python app/manage.py runserver 0.0.0.0:8000
  db:
    image: "postgis/postgis:12-3.0"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=snufkin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=snufkindb
