# Generated by Django 3.0.5 on 2020-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200503_0152'),
        ('trips', '0002_auto_20200503_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='place',
        ),
        migrations.AddField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(related_name='trips', to='places.Place'),
        ),
    ]
